export default function AiGeneratedBadge() {
  return (
    <span className="ai-badge-wrapper">
      <span className="inline-flex items-center gap-1 text-xs text-text-tertiary font-mono cursor-default">
        <span className="text-accent-purple">✦</span>
        <span>AI Generated</span>
      </span>
      <span className="ai-badge-tooltip">
        This content was generated by AI based on profile data and conversational inputs.
        It has not been manually reviewed or edited by the user. It is intended as a
        reasonable approximation of the user's views, not a direct quote or personal statement.
      </span>
    </span>
  )
}
