const STATUS_CONFIG = {
  ai_generated: {
    icon: '✦',
    label: 'AI generated, not reviewed',
    colorClass: 'text-accent-purple',
    tooltip: 'This content was generated by AI and has not yet been reviewed by a user.',
  },
  user_reviewed: {
    icon: '✓',
    label: 'User-reviewed and approved',
    colorClass: 'text-accent-green',
    tooltip: 'A user reviewed this content and marked it as approved.',
  },
  user_edited: {
    icon: '★',
    label: 'User-edited with personal experience',
    colorClass: 'text-accent-amber',
    tooltip: 'A user directly edited this content with personal context or lived experience.',
  },
}

function formatUpdatedBy(updatedBy) {
  if (!updatedBy) return null
  return String(updatedBy)
}

function formatUpdatedAt(updatedAt) {
  if (!updatedAt) return null
  const date = new Date(updatedAt)
  if (Number.isNaN(date.getTime())) return null
  return date.toLocaleString()
}

export default function ContentProvenanceBadge({ provenance, className = '' }) {
  const status = provenance?.status || 'ai_generated'
  const config = STATUS_CONFIG[status] || STATUS_CONFIG.ai_generated
  const updatedAt = formatUpdatedAt(provenance?.updated_at)
  const updatedBy = formatUpdatedBy(provenance?.updated_by)

  return (
    <span className={`provenance-badge-wrapper ${className}`.trim()}>
      <span className="inline-flex items-center gap-1 text-[11px] text-text-tertiary font-mono cursor-default">
        <span className={config.colorClass}>{config.icon}</span>
        <span>{config.label}</span>
      </span>
      <span className="provenance-badge-tooltip">
        {config.tooltip}
        {(updatedAt || updatedBy) && (
          <>
            <br />
            {updatedAt && <span>Updated: {updatedAt}</span>}
            {updatedAt && updatedBy && <span> · </span>}
            {updatedBy && <span>By: {updatedBy}</span>}
          </>
        )}
      </span>
    </span>
  )
}
